Repository camunda/camunda-docs-manual, pull requests merged in 2025-04, with the labels that each got.

#1758 chore(activityView): explain cancel activity badge
  content/webapps/cockpit/bpmn/process-instance-modification.md
  content/webapps/cockpit/bpmn/process-instance-view.md
  content/webapps/cockpit/img/cockpit-modification-cancel-done.png
  content/webapps/cockpit/img/cockpit-modification-cancel-in-progress.png
Labels: bot:backport:latest

#1759 chore(docs): migrate modeler c7 only docs from c8
  content/modeler/element-templates.md
  content/modeler/element-templates/img/custom-fields.png
  content/modeler/element-templates/img/default-errors-rendering.png
  content/modeler/element-templates/img/default-rendering.png
  content/modeler/element-templates/img/entries-visible.png
  content/modeler/element-templates/img/field-boolean.png
  content/modeler/element-templates/img/field-dropdown.png
  content/modeler/element-templates/img/groups.png
  content/modeler/element-templates/img/overview.png
  content/modeler/element-templates/img/scope-custom-fields.png
  content/modeler/history-time-to-live.md
Labels: bot:backport:7.21, bot:backport:7.22, bot:backport:latest

#1781 fix(download): fix community download link to point to C7 page
  content/introduction/downloading-camunda.md
Labels: bot:backport:7.21, bot:backport:7.20, bot:backport:7.19, bot:backport:7.22, bot:backport:latest, bot:backport:7.23
